### ISSUE TITLE
UMD build seems "broken" (when loading with Webpack)

### ISSUE THREAD

**Issue by cristiano-belloni** [websdk/nap#26]
Hi, that was the real issue underneath. I spoke a bit with Leon, and we concluded it's ok to have an UMD build published in NPM - after all it's a superset of commonjs.

We inspected what nap is publishing in depth and it seems that in the opening header, browserify is actually overwriting the `require` function to be something. This is not correct, imho, and prevents any module loader to correctly require rhumb from nap.

(compare with d3's closing UMD statement: https://github.com/mbostock/d3/blob/master/d3.js#L9549)

**Comment by mstade** [comment]
Browserify isn't being used in published version; it's babel that does the compilation, with the `--modules umd` flag set. I'm gonna have look right now to see what the heck is going on.

**Comment by mstade** [comment]
Sorry, please disregard my previous comment – I was looking at the wrong branch.

**Comment by mstade** [comment]
So, Browserify does have a pretty weird header, but I can't see that it overwrites `require` anywhere. Where did you see this?

**Comment by cristiano-belloni** [comment]
I mean that it has `require` as a param of the internal function. The internal function in turn calls `require('@websdk/rhumb')` and that excepts and dies for me.

I don't know what `--standalone` is doing, nut probably is not what we want?

**Comment by mstade** [comment]
@janesconference any chance you could push an example of this somewhere? I'm having a hard time understanding what about the build is actually broken here.

**Comment by mstade** [comment]
From the docs:

> `--standalone -s`
> Generate a UMD bundle for the supplied export name.
> This bundle works with other module systems and sets the name
> given as a window global if no module system is found.

That it passes along `require` as a parameter to the factory function shouldn't matter, because it picks it out of the runtime environment:

``` javascript
var a = typeof require == "function" && require;
```

**Comment by cristiano-belloni** [comment]
mmmh ok, I'll just push a branch of conversations that dies trying to require rhumb inside of nap. Maybe `require` is not runtime defined in the Webpack build? I'm puzzled.

**Comment by mstade** [comment]
Btw, this is highly useful testing so thank you very much! Once sorted, we should push a demo to `websdk/nap-examples`; there already is one for RequireJS but the more is definitely the merrier!

**Comment by cristiano-belloni** [comment]
https://github.com/zambezi-websdk/conversations/tree/nap-integration

Thank you for looking into this with me -- I guess many people would want to load `nap` with Webpack, and I just can't put my finger on what's wrong.

**Comment by cristiano-belloni** [comment]
Seems relevant: https://github.com/webpack/webpack/issues/319

> It is common best-practice to use the CommonJS-version of a library instead of requiring pre-built libs. They're even recommending it. Why don't you just require it so it will use the package.json's main file?
> 
> As @sokra pointed out: The problem is that browserify ships its own require()-implementation for the browserified library. That's an unnecessary overhead if you can just consume the CommonJS-version

But it seems resolved in the newest Webpack versions, so I'm still puzzled.

**Comment by mstade** [comment]
So I've created a simple demo that exhibits the same behavior, I think. I'm puzzled as well, but I'm inclined to say webpack is in the wrong here. Browserify when used to create standalone libraries _does not_ ship with its own require implementation, and doesn't really add any significant overhead.

The investigation continues...

**Comment by cristiano-belloni** [comment]
Just a (terribly general) question, Marcus - are we really sure we want to publish built-to-UMD libs to npm? it seems the current best practice is "if it's already common.js, just share the source".

I'm saying this because a lot of people currently use Webpack. If we start saying "ok, you can use our stuff with Wepack, but you have to tweak this and that in your configuration to make it work", the whole experience becomes a bit "cranky".

**Comment by mstade** [comment]
Ideally, I'd just push ES6 and be done with it, but that's a ways off and so UMD is the compatibility layer that gets us there. So yes, we _should_ push built-to-UMD as the main consumable, otherwise we're targeting specific environments and that's a can of worms I just don't want to open up.

Webpack is broken – plain and simple. I've debugged this and can see that the build fails because webpack fails to detect the `require('@websdk/rhumb')` call, so it's never included in the bundle. Even if you force it there, it will still fail because browserify calls out to the environments' `require` if it can't find the module definition in its own table. Webpack does include its own module lookup boilerplate, however it doesn't set the `require` identifier to point to webpack's lookup function. Instead, it does this rather retarded thing:

``` javascript
function(module, exports, __webpack_require__) {

    var require;
    var require;
    (function(f) {
```

Note the (double) `var require;` which will ensure `require` is always undefined. It'd be undefined in the browser _anyway_ (which could be fixed by doing `var require = __webpack_require__`) but by doing that they ensure the bundle won't work in environment where the require function _does_ exist – such as node.

I agree, we should play nice in the tooling space, but the solution to having a broken tool is to fix the tool, not hack the libraries you want to use the tool with.

**Comment by mstade** [comment]
So to sum it up, there are a couple of issues at play here:
1. webpack, for whatever reason, fails to see the `require('@rhumb/websdk')` call
2. even if webpack did see it, and does include `@rhumb/websdk`, it'll still fail because webpack doesn't delegate `require` calls to its own lookup function

I'm currently looking through webpack's issues to try and find other people with the same problem, and what they're doing to solve it.

**Comment by cristiano-belloni** [comment]
It fails to do the static analysis and replacement because Browserify has another variable called `require` in the function scope - how can Webpack tell if this particular `require` (which is not the global one, but just an aliasing scope variable) has to be replaced or not? Imho, it's browserify that does the wrong thing monkey-patching require, here.

I'm convinced the whole "Webpack supports this, but > 1.3.0" thing is for bundled libraries (that contain all the dependencies), so it won't work in our case :/

**Comment by cristiano-belloni** [comment]
Would `var require = __webpack_require__` and then `require('@websdk/rhumb')` even work? I guess the namespace of modules inside Webpack is different from npm's.

I think they are all compiled to stuff like `__webpack_require__(12)`.

**Comment by mstade** [comment]
Browserify never monkey patches `require`. What it does is proxy it, so that it can provide whatever modules were bundled _by_ browserify, as opposed to letting the global `require` deal with it. If the proxy can't find the module in the included bundle, it'll just pass on to the global `require` _if it exists_. That latter part is the problem here: webpack doesn't proxy `require` to its own loader, which means _any_ call out to require, regardless of who makes it or for whatever reason _will_ fail.

All evidence I can find suggests webpack is broken, and I'm trying to figure out what to do about it. My current plan is to change the build to produce a UMD without the browserify boilerplate – we don't need it anyway, since we don't bundle _any_ dependencies. Just bear with me for a moment. :o)

**Comment by mstade** [comment]
You're probably right about that, but it'd be trivial for webpack to provide it's own mapping from string to id.

**Comment by mstade** [comment]
Sorry, re-reading your comment I understand what you mean now about webpack doing the analysis and figuring that because there's a _local_ require variable, it shouldn't much about with assuming it's a module lookup function. That's probably the right thing to do, but it wouldn't be terribly difficult for them to apply heuristics to understand the boilerplate and deal with it appropriately.

In any event, the solution; I'm sure, is to not bundle anything anyway. I'll push a PR in a few that should hopefully fix this!

**Comment by cristiano-belloni** [comment]
> but it wouldn't be terribly difficult for them to apply heuristics to understand the boilerplate and deal with it appropriately.

Agree with you on this, but I guess if they do, they get a load of complaints from people that alias `require` for whatever reason and don't want webpack to intrusively change that :)

> In any event, the solution; I'm sure, is to not bundle anything anyway. I'll push a PR in a few that should hopefully fix this!

+1000.

**Comment by mstade** [comment]
Well, the heuristics I had in mind would be pretty specific to browserify. It can (and should, probably) be argued that if you do it for browserify then you also have to do it for all the other bundling formats out there. But given browserify is the only _other_ bundler with any real presence in reality it wouldn't be a big deal.

Anyway, sorry that you had to run head first into this buddy. I'm pretty sure I've got a fix sorted and will be pushing it asap, just gotta do some testing..

**Comment by cristiano-belloni** [comment]
> Anyway, sorry that you had to run head first into this buddy.

I familiarized a bit with browserify and learnt more about webpack, so it's actually all good! :)

> I'm pretty sure I've got a fix sorted and will be pushing it asap, just gotta do some testing..

Thank you very much for your help on this!

**Comment by mstade** [comment]
Alright buddy, #27 should solve your problem. At least, it did when I tested it in my little project. I'll push my thing to nap-examples as well, it's a good little reference case – thanks for bringing this up!

I'm gonna close this in favor of #27. Feel free to re-open (or just continue the discussion over there) if you feel different about it!
